package org.firstinspires.ftc.teamcode.framework.ctlpad.CTL2Java;

import com.qualcomm.robotcore.hardware.Gamepad;
import org.firstinspires.ftc.teamcode.framework.units.DTS;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.Axis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.Button;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.ButtonAsAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.ExponentialAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.LinearAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.MergedAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.AxisAsButton;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.MomentaryButton;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.ToggleButton;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.TriggerButton;



import org.firstinspires.ftc.teamcode.framework.ctlpad.CTL2Java.test.TestSchemeInterface;
import org.firstinspires.ftc.teamcode.framework.ctlpad.CTL2Java.test.TestSchemeState;

/** This control scheme was generated by CTL2Java. */
public class CTLtest implements TestSchemeInterface {
	

	private Gamepad gamepad1;
	private Gamepad gamepad2;
	TestSchemeState state;	

	private Button OneADefault;
	private Button OneAX;
	private Button OneAY;
	private Button OneBDefault;
	private Axis OneR2Default;
	private MomentaryButton OneX;
	private MomentaryButton OneY;

	
	public CTLtest(Gamepad gamepad1, Gamepad gamepad2) {
		this.gamepad1 = gamepad1;
		this.gamepad2 = gamepad2;
		state = new TestSchemeState();
		
		OneADefault = new MomentaryButton( () -> gamepad1.a );
		OneAX = new ToggleButton( () -> gamepad1.a );
		OneAY = new MomentaryButton( () -> gamepad1.a );
		OneBDefault = new MomentaryButton( () -> gamepad1.b );
		OneR2Default = new LinearAxis( () -> gamepad1.right_trigger, 0.5 );
		OneX = new MomentaryButton( () -> gamepad1.x );
		OneY = new MomentaryButton( () -> gamepad1.y );
}

	void setActionOne() {
		// START ActionOne
	state.setActionOne( OneADefault.isActive() );
	// END ActionOne
	

		// Indy Drive Type
	}

	void setActionTwo() {
		// START ActionTwo
	state.setActionTwo( OneR2Default.value() * 0.25 );
	// END ActionTwo
	

	}

	void setModifierActionOne() {
	if (OneX.isActive()) {
	// START ModifierActionOne
	state.setModifierActionOne( OneAX.isActive() );
	// END ModifierActionOne
	
	}

		// START Extension Action
	// START ModifierActionOne
	state.setModifierActionOne( OneBDefault.isActive() );
	// END ModifierActionOne
	// START ModifierActionTwo
	state.setModifierActionTwo( OneBDefault.isActive() );
	// END ModifierActionTwo
	state.setActionTwo( state.getActionTwo() + 0.2 );
	// END Extension Action
	

	}

	void setModifierActionTwo() {
	if (OneY.isActive()) {
	// START ModifierActionTwo
	state.setModifierActionTwo( OneAY.isActive() );
	// END ModifierActionTwo
	
	}

	}


	
	@Override
	public org.firstinspires.ftc.teamcode.framework.ctlpad.CTL2Java.test.TestSchemeState getState() {
		setActionOne();
		setActionTwo();
		setModifierActionOne();
		setModifierActionTwo();

		
		return state;
	}
}

