package org.firstinspires.ftc.teamcode.framework.ctlpad.CTL2Java;

import com.qualcomm.robotcore.hardware.Gamepad;
import org.firstinspires.ftc.teamcode.framework.units.DTS;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.Axis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.Button;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.ButtonAsAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.ExponentialAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.LinearAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.MergedAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.AxisAsButton;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.MomentaryButton;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.ToggleButton;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.TriggerButton;



import org.firstinspires.ftc.teamcode.framework.ctlpad.CTL2Java.test.TestSchemeInterface;
import org.firstinspires.ftc.teamcode.framework.ctlpad.CTL2Java.test.TestSchemeState;

/** This control scheme was generated by CTL2Java. */
public class CTLtest implements TestSchemeInterface {
	

	private Gamepad gamepad1;
	private Gamepad gamepad2;
	TestSchemeState state;	

	private Button OneADefault;
	private Button OneAX;
	private Button OneAY;
	private Button OneBDefault;
	private Axis OneR2Default;

	
	public CTLtest(Gamepad gamepad1, Gamepad gamepad2) {
		this.gamepad1 = gamepad1;
		this.gamepad2 = gamepad2;
		state = new TestSchemeState();
		
		OneADefault = new MomentaryButton( () -> gamepad1.a );
		OneAX = new ToggleButton( () -> gamepad1.a );
		OneAY = new MomentaryButton( () -> gamepad1.a );
		OneBDefault = new MomentaryButton( () -> gamepad1.b );
		OneR2Default = new LinearAxis( () -> gamepad1.right_trigger, 0.5 );
}

	void setActionOne() {
		state.setActionOne( OneADefault.isActive() );
	

		// Indy Drive Type
	}

	void setActionTwo() {
		state.setActionTwo( OneR2Default.value() * 0.25 );
	

	}

	void setModifierActionOne() {
		state.setModifierActionOne( OneAX.isActive() );
	

		state.setModifierActionOne( OneBDefault.isActive() );
	state.setModifierActionTwo( OneBDefault.isActive() );
	state.setActionTwo( state.getActionTwo() + 0.2 );
	// Extension Action
	

	}

	void setModifierActionTwo() {
		state.setModifierActionTwo( OneAY.isActive() );
	

	}


	
	@Override
	public org.firstinspires.ftc.teamcode.framework.ctlpad.CTL2Java.test.TestSchemeState getState() {
		setActionOne();
		setActionTwo();
		setModifierActionOne();
		setModifierActionTwo();

		
		return state;
	}
}

