package org.firstinspires.ftc.teamcode.framework.ctlpad.CTL2Java;

import com.qualcomm.robotcore.hardware.Gamepad;
import org.firstinspires.ftc.teamcode.framework.units.DTS;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.Axis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.Button;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.ButtonAsAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.ExponentialAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.LinearAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.axes.MergedAxis;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.AxisAsButton;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.MomentaryButton;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.ToggleButton;
import org.firstinspires.ftc.teamcode.framework.ctlpad.primitives.buttons.TriggerButton;

import org.firstinspires.ftc.teamcode.fy25.subsystems.launcherwheel.LauncherWheel;
import org.firstinspires.ftc.teamcode.fy25.subsystems.launchergate.LauncherGate;
import org.firstinspires.ftc.teamcode.fy25.subsystems.motorintake.MotorIntake;

import org.firstinspires.ftc.teamcode.fy25.ctlpad.StarterBotScheme25;
import org.firstinspires.ftc.teamcode.fy25.ctlpad.StarterBotState25;

/** This control scheme was generated by CTL2Java. */
public class fy25test implements StarterBotScheme25 {
	

	private Gamepad gamepad1;
	private Gamepad gamepad2;
	StarterBotState25 state;	

	private Button OneStartDefault;
	private Button OneSelectDefault;
	private Axis OneLSXDefault;
	private Axis OneRSXDefault;
	private Axis OneR2Default;
	private Axis OneL2Default;
	private Axis OneMergedR2L2Default;
	private Button TwoADefault;
	private Button TwoBDefault;
	private Button TwolauncherGateInDefault;
	private Button TwoL1Default;
	private Button TwolauncherWheelSpinUpDefault;
	private Button TwoR1Default;
	private Axis TwoR2Default;
	private Axis TwoL2Default;

	
	public fy25test(Gamepad gamepad1, Gamepad gamepad2) {
		this.gamepad1 = gamepad1;
		this.gamepad2 = gamepad2;
		state = new StarterBotState25();
		
		OneStartDefault = new TriggerButton( () -> gamepad1.start );
		OneSelectDefault = new TriggerButton( () -> gamepad1.back );
		OneLSXDefault = new ExponentialAxis( () -> gamepad1.left_stick_x, 2.0 );
		OneRSXDefault = new LinearAxis( () -> gamepad1.right_stick_x, 1.0 );
		OneR2Default = new LinearAxis( () -> gamepad1.right_trigger, 1.0 );
		OneL2Default = new LinearAxis( () -> gamepad1.left_trigger, 1.0 );
		TwoADefault = new TriggerButton( () -> gamepad2.a );
		TwoBDefault = new TriggerButton( () -> gamepad2.b );
		TwoL1Default = new TriggerButton( () -> gamepad2.left_bumper );
		TwoR1Default = new TriggerButton( () -> gamepad2.right_bumper );
		TwoR2Default = new LinearAxis( () -> gamepad2.right_trigger, 1.0 );
		TwoL2Default = new LinearAxis( () -> gamepad2.left_trigger, 1.0 );
		TwolauncherGateInDefault = new AxisAsButton( new LinearAxis( () -> gamepad2.left_trigger ), 0.1  );
		TwolauncherWheelSpinUpDefault = new AxisAsButton( new LinearAxis( () -> gamepad2.right_trigger ), 0.1  );
		OneMergedR2L2Default = new MergedAxis( OneL2Default, OneR2Default );
}

	void setIntakeVel() {
	
	
	}

	void setLaunchVel() {
	
	
	}

	void setDts() {
		double drive = 0;
		boolean driveSet = false;
			double driveVal = OneMergedR2L2Default.value();
		if ( !driveSet && !( -0.01 < driveVal && driveVal < 0.01 ) ) {
			drive = OneMergedR2L2Default.value();
			driveSet = true;
		}
		

		
		double turn = 0;
		boolean turnSet = false;
			double turnVal = OneLSXDefault.value();
		if ( !turnSet && ! ( -0.01 < turnVal && turnVal < 0.01 ) ) {
			turn = OneLSXDefault.value();
			turnSet = true;
		}
		

		
		double strafe = 0;
		boolean strafeSet = false;
			double strafeVal = OneRSXDefault.value();
		if ( !strafeSet && !( -0.01 < strafeVal && strafeVal < 0.01 ) ) {
			strafe = OneRSXDefault.value();
			strafeSet = true;
		}
		

		
		state.setDts( new DTS( drive, turn, strafe ) );
	}

	void setMotorIntakeState() {
			if ( TwoADefault.isActive() ) {
			state.setMotorIntakeState( MotorIntake.State.RUNIN );
		}
		

			if ( TwoBDefault.isActive() ) {
			state.setMotorIntakeState( MotorIntake.State.RUNOUT );
		}
		

	}

	void setRunLaunchWheel() {
			if ( TwolauncherWheelSpinUpDefault.isActive() ) {
			state.setRunLaunchWheel( true );
		}
		

			if ( TwoR1Default.isActive() ) {
			state.setRunLaunchWheel( false );
		}
		

	}

	void setLauncherGateState() {
			if ( TwolauncherGateInDefault.isActive() ) {
			state.setLauncherGateState( LauncherGate.State.OPEN );
		}
		

			if ( TwoL1Default.isActive() ) {
			state.setLauncherGateState( LauncherGate.State.CLOSED );
		}
		

	}

	void setMaxDriveSpeed() {
			if ( OneStartDefault.isActive() ) {
			state.setMaxDriveSpeed( state.getMaxDriveSpeed() + 0.1 );
		}
		
		if ( OneSelectDefault.isActive() ) {
			state.setMaxDriveSpeed( state.getMaxDriveSpeed() + -0.1 );
		}
		

	
	}

	void setSquareUp() {
	
	}


	
	@Override
	public org.firstinspires.ftc.teamcode.fy25.ctlpad.StarterBotState25 getState() {
		setIntakeVel();
		setLaunchVel();
		setDts();
		setMotorIntakeState();
		setRunLaunchWheel();
		setLauncherGateState();
		setMaxDriveSpeed();
		setSquareUp();

		
		return state;
	}
}

